//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geekshirt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int UID { get; set; }
        public int LID { get; set; }
        public int TotalPrice { get; set; }
    
        public virtual ShopLists ShopLists { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
