//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geekshirt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopLists
    {
        public ShopLists()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ListID { get; set; }
        public Nullable<int> AID { get; set; }
        public int UID { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
