//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geekshirt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public UserData()
        {
            this.Orders = new HashSet<Orders>();
            this.ShopLists = new HashSet<ShopLists>();
        }
    
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public int UID { get; set; }
    
        public virtual UserLogIn UserLogIn { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<ShopLists> ShopLists { get; set; }
    }
}
